/// Flutter icons Profileicon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Profileicon
///      fonts:
///       - asset: fonts/Profileicon.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Profileicon {
  Profileicon._();

  static const _kFontFam = 'Profileicon';
  static const String? _kFontPkg = null;

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rate_us = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData faq = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData directions = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData view_agenda = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share_app = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact_us__1_ = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
